# Common Labels
labels:
  app: "digit-ui"
  group: "web"

# Ingress Configs
ingress:
  enabled: true
  context: "digit-ui"

# Init Containers Configs
initContainers: {}

# Container Configs
image:
  repository: "digit-ui"
replicas: "1"
httpPort: 80
healthChecks:
  enabled: true
  livenessProbePath: "/digit-ui/"
  readinessProbePath: "/digit-ui/"

namespace: egov    
